### ISSUE TITLE
Default `kitty_local`

### ISSUE THREAD

**Issue by huyz** [webarch-coop/ansible-role-kitty#1]
Perhaps the default `kitty_local` should be set to `~/.local/kitty.app` since that's what Kitty's installer does.

**Comment by chriscroome** [comment]
Thanks for all the suggestions @huyz -- do the latest updates solve all three issues?

**Comment by huyz** [comment]
@chriscroome Thanks for the quick turnaround. I mentioned a couple of bugs in your commit https://github.com/webarch-coop/ansible-role-kitty/commit/8989d8aa79d6ae43a331358edcff5a1959986ce9#diff-3d0ff1709ca48add100327bb2a468e6c508fb92a159c64c4f99ad1df89d9bddeR183

**Comment by chriscroome** [comment]
Fixed in [version 1.1.0](https://github.com/webarch-coop/ansible-role-kitty/releases/tag/1.1.0).
