### ISSUE TITLE
[FR] add symlinks and desktop files

### ISSUE THREAD

**Issue by huyz** [webarch-coop/ansible-role-kitty#2]
as per https://sw.kovidgoyal.net/kitty/binary/#desktop-integration-on-linux

**Comment by chriscroome** [comment]
Fixed in [version 1.1.0](https://github.com/webarch-coop/ansible-role-kitty/releases/tag/1.1.0).

**Comment by huyz** [comment]
Actually, the `~` in the default variables won't expand inside the `.desktop` files.
But this will work:
```
    kitty_bin: "{{ ansible_env.HOME }}/.local/bin"
    kitty_local: "{{ ansible_env.HOME }}/.local/kitty.app"
```

**Comment by chriscroome** [comment]
Thanks for checking that, I use [sway](https://swaywm.org/) these days so never actually use any `.desktop` files&hellip; Hopefully it is fixed in [1.1.1](https://github.com/webarch-coop/ansible-role-kitty/releases/tag/1.1.1)?

**Comment by huyz** [comment]
Interesting about Sway. I've been using https://github.com/pop-os/shell but I should check out Sway.

**Comment by chriscroome** [comment]
Sway does lack some things compared with Gnome, if Pop Shell was in Debian with Wayland support I'd give it a try.

**Comment by huyz** [comment]
@chriscroome You have a typo:
```
kitty_bin: "{{ ansible_env.HOME }}/.local/bin"
```
not
```
kitty_bin: "{{ ansible_env.HOME }}/.local/bin }}"
```

**Comment by chriscroome** [comment]
Thanks for spotting that @huyz hopefully it is all good now!

**Comment by huyz** [comment]
@chriscroome How does Galaxy get the new version? I can't seem to pull 1.1.2 from there.

**Comment by chriscroome** [comment]
Sorry, I've updated it now:

https://galaxy.ansible.com/chriscroome/kitty

Galaxy doesn't automatically pull in updates from GitHub, it has to be done manually and I forgot to do it after the last release.
