### ISSUE TITLE
[FR] auto-cleanup

### ISSUE THREAD

**Issue by huyz** [webarch-coop/ansible-role-kitty#4]
Hello again.

What do you think about cleaning up the downloads in the temp directory after installation is done?

**Comment by chriscroome** [comment]
Good idea, would you like to test the main branch to see if it works as expected?

I haven't added the deleting of the GPG public key since that probably isn't going to change very often.

**Comment by huyz** [comment]
@chriscroome It worked. Thanks!

**Comment by chriscroome** [comment]
Great, I've released version `1.2.0` and it is available via [Galaxy](https://galaxy.ansible.com/chriscroome/kitty).
